events {

}

error_log /dev/stdout info;

http {
	server {
		listen 0.0.0.0:80 default_server;
		proxy_pass_request_headers on;
		include /etc/nginx/mime.types;
		access_log /dev/stdout;

		charset     utf-8;

		location /media/private/ {
			return 403;
		}

		location /media/ {
			alias /app/media/;
			access_log off;
			# autoindex on;

			add_header Cache-Control "public, max-age=604800, immutable"; # 1 week
		}
	}
}