import type { ChatsDataType, ChatType } from '../../shared/types';
import showplsAgentIcon from '../../assets/logo-without-text.svg';

export const chatList: ChatType[] = [
  {
    chat_id: 1,
    avatar: showplsAgentIcon,
    first_name: 'Showpls',
    last_name: 'Agent',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 2,
    avatar: null,
    first_name: 'Name no surname',
    last_name: null,
    last_message: 'Lorem ipsum dolor sit amet consectetur',
    last_update: 1760453955290,
    is_favorite: true,
    is_active_order: true,
    count_unread: 1,
    is_read: false,
  },
  {
    chat_id: 3,
    avatar:
      'https://t.me/i/userpic/320/q4sKbvOxAfs1GzG1BvCxGsS2dLs62WaTHYUrqguxs_M.svg',
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 4,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message: 'Lorem ipsum dolor sit amet consectetur',
    last_update: 1760453955290,
    is_favorite: true,
    is_active_order: true,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 5,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: true,
    count_unread: 15,
    is_read: false,
  },
  {
    chat_id: 6,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 7,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: true,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 8,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    count_unread: 4,
    is_read: false,
  },
  {
    chat_id: 9,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 10,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 11,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 12,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 13,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 14,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 15,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 16,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 17,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 18,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 19,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 20,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 21,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
  {
    chat_id: 22,
    avatar: null,
    first_name: 'Name',
    last_name: 'Surname',
    last_message:
      'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien.',
    last_update: 1760453955290,
    is_favorite: false,
    is_active_order: false,
    is_read: true,
    count_unread: null,
  },
];

export const chatsData: ChatsDataType = {
  count_unread: 3,
  count_unread_favorite: 1,
  chat_list: chatList,
};
