import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1765016242418 implements MigrationInterface {
    name = 'InitialSchema1765016242418'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "stars_top_up" ("id" BIGSERIAL NOT NULL, "txid" character varying(255), "amount" bigint NOT NULL, "paid" boolean NOT NULL, "link" character varying(255) NOT NULL, "refunded" boolean NOT NULL DEFAULT false, "userId" bigint NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f63236770f620ed1c038f18cae0" UNIQUE ("txid"), CONSTRAINT "PK_8bb32156caa62718db4f2be6985" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ton_top_up_token_enum" AS ENUM('STARS', 'TON', 'USDT')`);
        await queryRunner.query(`CREATE TABLE "ton_top_up" ("id" BIGSERIAL NOT NULL, "txid" character varying(255), "amount" numeric(78,0), "token" "public"."ton_top_up_token_enum", "paid" boolean NOT NULL, "memo" BIGSERIAL NOT NULL, "userId" bigint NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c94589821a126f9bedc1d8cdc63" UNIQUE ("txid"), CONSTRAINT "UQ_df9406bd665d3a367b007606e35" UNIQUE ("memo"), CONSTRAINT "PK_8e40ec5b79d810bc954ce7ff951" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lastMessage" text, "countUnread" integer NOT NULL DEFAULT '0', "countUnread2" integer NOT NULL DEFAULT '0', "isActiveOrder" boolean NOT NULL DEFAULT false, "isArbitration" boolean NOT NULL DEFAULT false, "isFavorite" boolean NOT NULL DEFAULT false, "isFavorite2" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastUpdate" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user1Id" bigint, "user2Id" bigint, "adminId" bigint, CONSTRAINT "PK_9d0b2ba74336710fd31154738a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."deal_status_enum" AS ENUM('accepted', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."deal_escrowstatus_enum" AS ENUM('locked', 'released', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "deal" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."deal_status_enum" NOT NULL DEFAULT 'accepted', "escrowStatus" "public"."deal_escrowstatus_enum", "arbitrationApproved" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "requestId" uuid, "responseId" uuid, "customerId" bigint, "performerId" bigint, "chatId" uuid, CONSTRAINT "PK_9ce1c24acace60f6d7dc7a7189e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."response_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "response" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."response_status_enum" NOT NULL DEFAULT 'pending', "message" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "requestId" uuid, "performerId" bigint, CONSTRAINT "PK_f64544baf2b4dc48ba623ce768f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."submission_status_enum" AS ENUM('pending', 'submitted', 'accepted', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "submission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "proofMeta" jsonb, "serverTs" TIMESTAMP NOT NULL, "status" "public"."submission_status_enum" NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "requestId" uuid NOT NULL, "performerId" bigint NOT NULL, CONSTRAINT "PK_7faa571d0e4a7076e85890c9bd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file_attachment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying(2048) NOT NULL, "hash" character varying(64) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "requestId" uuid, "submissionId" uuid, CONSTRAINT "PK_a0eab2f76759984a1dfa00a5d1f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."request_status_enum" AS ENUM('draft', 'published', 'accepted', 'in_progress', 'completed', 'cancelled', 'arbitration')`);
        await queryRunner.query(`CREATE TABLE "request" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "description" text NOT NULL, "price" numeric(10,2) NOT NULL, "location" geometry(Point,4326) NOT NULL, "status" "public"."request_status_enum" NOT NULL DEFAULT 'draft', "expiresAt" TIMESTAMP, "deadlineAt" TIMESTAMP, "acceptedAt" TIMESTAMP, "completedAt" TIMESTAMP, "cancelledAt" TIMESTAMP, "address" character varying(500), "metadata" jsonb, "isUrgent" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "customerId" bigint NOT NULL, CONSTRAINT "PK_167d324701e6867f189aed52e18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('admin', 'normal')`);
        await queryRunner.query(`CREATE TYPE "public"."user_languagecode_enum" AS ENUM('en', 'ru')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" BIGSERIAL NOT NULL, "role" "public"."user_role_enum" NOT NULL, "tgId" bigint NOT NULL, "username" character varying(255), "firstName" character varying(255) NOT NULL, "lastName" character varying(255), "avatar" character varying(255), "languageCode" "public"."user_languagecode_enum" NOT NULL, "banned" boolean NOT NULL, "lastSeenAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lastKnownLocation" geometry(Point,4326), "locationUpdatedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE ("username"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ton_ignored_transaction" ("id" BIGSERIAL NOT NULL, "txid" character varying(255) NOT NULL, "reason" text NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2c19230ded0e762f55e72556f67" UNIQUE ("txid"), CONSTRAINT "PK_8c0099b2d2d2b0cd061c8479ec4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."chat_message_type_enum" AS ENUM('message', 'notification')`);
        await queryRunner.query(`CREATE TABLE "chat_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."chat_message_type_enum" NOT NULL DEFAULT 'message', "variant" character varying, "text" text, "attachments" text array NOT NULL DEFAULT '{}', "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "chatId" uuid, "senderId" bigint, "receiverId" bigint, CONSTRAINT "PK_3cc0d85193aade457d3077dd06b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."arbitration_status_enum" AS ENUM('pending', 'resolved')`);
        await queryRunner.query(`CREATE TYPE "public"."arbitration_resolution_enum" AS ENUM('approve_cancel', 'complete', 'reject')`);
        await queryRunner.query(`CREATE TABLE "arbitration" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reason" text NOT NULL, "attachments" jsonb, "status" "public"."arbitration_status_enum" NOT NULL DEFAULT 'pending', "resolution" "public"."arbitration_resolution_enum", "adminMessage" text, "resolvedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "requestId" uuid NOT NULL, "chatId" uuid NOT NULL, "initiatorId" bigint NOT NULL, "resolvedById" bigint, CONSTRAINT "PK_a3bb213eaff42d0f31759bf37ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "text" text NOT NULL, "type" character varying NOT NULL, "variant" character varying, "payload" jsonb, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" bigint, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" BIGSERIAL NOT NULL, CONSTRAINT "CHK_b5d65c31b6e3559e2c66ca9525" CHECK (id = 1), CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_type_enum" AS ENUM('create-deposit', 'revert-deposit', 'escrow-hold', 'escrow-release', 'escrow-refund')`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_status_enum" AS ENUM('pending', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_initiatortype_enum" AS ENUM('user')`);
        await queryRunner.query(`CREATE TABLE "transaction" ("id" BIGSERIAL NOT NULL, "externalType" character varying(255), "externalId" character varying(255), "type" "public"."transaction_type_enum" NOT NULL, "status" "public"."transaction_status_enum" NOT NULL, "postedAt" TIMESTAMP WITH TIME ZONE, "initiatorType" "public"."transaction_initiatortype_enum" NOT NULL, "initiatorId" bigint, "meta" jsonb NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_6245c729867f07dde3f93c3a8e" CHECK (("externalId" IS NOT NULL AND "externalType" IS NOT NULL) OR ("externalId" IS NULL AND "externalType" IS NULL)), CONSTRAINT "PK_89eadb93a89810556e1cbcd6ab9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_279024522b83ec4b7ad9dadd33" ON "transaction" ("externalType", "externalId", "type") `);
        await queryRunner.query(`CREATE TABLE "entry" ("id" BIGSERIAL NOT NULL, "amount" numeric(78,0) NOT NULL, "currencyId" bigint NOT NULL, "accountId" bigint NOT NULL, "transactionId" bigint NOT NULL, "meta" jsonb NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a58c675c4c129a8e0f63d3676d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "currency" ("id" BIGSERIAL NOT NULL, "code" character varying(10) NOT NULL, "name" character varying(50) NOT NULL, "scale" integer NOT NULL, "blockchain" character varying(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_7ebdf976ae4e0adc3afbbf07d7" CHECK (scale >= 0 AND scale <= 18), CONSTRAINT "PK_3cda65c731a6264f0e444cc9b91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_006353a90dd7cf474171544cc9" ON "currency" ("code", "blockchain") `);
        await queryRunner.query(`CREATE TABLE "balance" ("id" BIGSERIAL NOT NULL, "currencyId" bigint NOT NULL, "accountId" bigint NOT NULL, "amount" numeric(78,0) NOT NULL, "lockedAmount" numeric(78,0) NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "CHK_e5834f908c37b14d6f40a3aca3" CHECK ("amount" >= 0 AND "lockedAmount" >= 0), CONSTRAINT "PK_079dddd31a81672e8143a649ca0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a1b37aa58d62564fe58dd8699d" ON "balance" ("currencyId", "accountId") `);
        await queryRunner.query(`CREATE TYPE "public"."account_purpose_enum" AS ENUM('main')`);
        await queryRunner.query(`CREATE TYPE "public"."account_ownertype_enum" AS ENUM('user', 'platform', 'escrow', 'external')`);
        await queryRunner.query(`CREATE TABLE "account" ("id" BIGSERIAL NOT NULL, "purpose" "public"."account_purpose_enum" NOT NULL, "ownerType" "public"."account_ownertype_enum" NOT NULL, "ownerId" bigint, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_33030f55bdd02bdb23a0bcdde7" ON "account" ("purpose", "ownerType", "ownerId") `);
        await queryRunner.query(`ALTER TABLE "stars_top_up" ADD CONSTRAINT "FK_3fe88363a4fa35788cc07495ba6" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ton_top_up" ADD CONSTRAINT "FK_3de8252da69a30a57dcdbe5fb2b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat" ADD CONSTRAINT "FK_e263d1c2fdcbc5a97216a28e226" FOREIGN KEY ("user1Id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat" ADD CONSTRAINT "FK_99f86fa5d1a0f13f9cbbeae3120" FOREIGN KEY ("user2Id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat" ADD CONSTRAINT "FK_338e1e9cdacd1d28d7ca9999d8d" FOREIGN KEY ("adminId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deal" ADD CONSTRAINT "FK_4e3561769b30678661c19bd6c83" FOREIGN KEY ("requestId") REFERENCES "request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deal" ADD CONSTRAINT "FK_bfbf920d6a1138fa110db3e4bac" FOREIGN KEY ("responseId") REFERENCES "response"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deal" ADD CONSTRAINT "FK_cef8a02fad2477f5391c15d28ff" FOREIGN KEY ("customerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deal" ADD CONSTRAINT "FK_2f614e9e5a1934a795c5899ccef" FOREIGN KEY ("performerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deal" ADD CONSTRAINT "FK_4e612f6283969396f800e463928" FOREIGN KEY ("chatId") REFERENCES "chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "response" ADD CONSTRAINT "FK_d8eecba590e554b8a3fdaa884f0" FOREIGN KEY ("requestId") REFERENCES "request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "response" ADD CONSTRAINT "FK_f6f1d760569e3565113b2806610" FOREIGN KEY ("performerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submission" ADD CONSTRAINT "FK_06b7f04c92b02a7cf982ce2d417" FOREIGN KEY ("requestId") REFERENCES "request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "submission" ADD CONSTRAINT "FK_ad5269fea384294bcd8a641b2ff" FOREIGN KEY ("performerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_attachment" ADD CONSTRAINT "FK_b74e260931fa11b0aab911850cb" FOREIGN KEY ("requestId") REFERENCES "request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_attachment" ADD CONSTRAINT "FK_164487104dbf53af0ae6603044d" FOREIGN KEY ("submissionId") REFERENCES "submission"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request" ADD CONSTRAINT "FK_ea494d8562edd5a4bb96a9092ea" FOREIGN KEY ("customerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_6d2db5b1118d92e561f5ebc1af0" FOREIGN KEY ("chatId") REFERENCES "chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_a2be22c99b34156574f4e02d0a0" FOREIGN KEY ("senderId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_d387aec1bec2ca593b517deb6dc" FOREIGN KEY ("receiverId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arbitration" ADD CONSTRAINT "FK_6571aebe2c67f894438c97dc993" FOREIGN KEY ("requestId") REFERENCES "request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arbitration" ADD CONSTRAINT "FK_067e5339130b83c412c9eb8a0b6" FOREIGN KEY ("chatId") REFERENCES "chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arbitration" ADD CONSTRAINT "FK_48434413d72a7d04cf92f1e1a32" FOREIGN KEY ("initiatorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arbitration" ADD CONSTRAINT "FK_6e8557bf51cd6cc77f9fc0fb07e" FOREIGN KEY ("resolvedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_1ced25315eb974b73391fb1c81b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entry" ADD CONSTRAINT "FK_7cda6e23f278ae51b973cdc19fe" FOREIGN KEY ("currencyId") REFERENCES "currency"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entry" ADD CONSTRAINT "FK_dc23c864c9270f1d5f0bf0dfea3" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "entry" ADD CONSTRAINT "FK_182a7b614924472da44fae1be54" FOREIGN KEY ("transactionId") REFERENCES "transaction"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "balance" ADD CONSTRAINT "FK_c856fcc5cd8aef4dfda1a6e04f0" FOREIGN KEY ("currencyId") REFERENCES "currency"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "balance" ADD CONSTRAINT "FK_7ee384741a490213486471471d4" FOREIGN KEY ("accountId") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "balance" DROP CONSTRAINT "FK_7ee384741a490213486471471d4"`);
        await queryRunner.query(`ALTER TABLE "balance" DROP CONSTRAINT "FK_c856fcc5cd8aef4dfda1a6e04f0"`);
        await queryRunner.query(`ALTER TABLE "entry" DROP CONSTRAINT "FK_182a7b614924472da44fae1be54"`);
        await queryRunner.query(`ALTER TABLE "entry" DROP CONSTRAINT "FK_dc23c864c9270f1d5f0bf0dfea3"`);
        await queryRunner.query(`ALTER TABLE "entry" DROP CONSTRAINT "FK_7cda6e23f278ae51b973cdc19fe"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_1ced25315eb974b73391fb1c81b"`);
        await queryRunner.query(`ALTER TABLE "arbitration" DROP CONSTRAINT "FK_6e8557bf51cd6cc77f9fc0fb07e"`);
        await queryRunner.query(`ALTER TABLE "arbitration" DROP CONSTRAINT "FK_48434413d72a7d04cf92f1e1a32"`);
        await queryRunner.query(`ALTER TABLE "arbitration" DROP CONSTRAINT "FK_067e5339130b83c412c9eb8a0b6"`);
        await queryRunner.query(`ALTER TABLE "arbitration" DROP CONSTRAINT "FK_6571aebe2c67f894438c97dc993"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_d387aec1bec2ca593b517deb6dc"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_a2be22c99b34156574f4e02d0a0"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_6d2db5b1118d92e561f5ebc1af0"`);
        await queryRunner.query(`ALTER TABLE "request" DROP CONSTRAINT "FK_ea494d8562edd5a4bb96a9092ea"`);
        await queryRunner.query(`ALTER TABLE "file_attachment" DROP CONSTRAINT "FK_164487104dbf53af0ae6603044d"`);
        await queryRunner.query(`ALTER TABLE "file_attachment" DROP CONSTRAINT "FK_b74e260931fa11b0aab911850cb"`);
        await queryRunner.query(`ALTER TABLE "submission" DROP CONSTRAINT "FK_ad5269fea384294bcd8a641b2ff"`);
        await queryRunner.query(`ALTER TABLE "submission" DROP CONSTRAINT "FK_06b7f04c92b02a7cf982ce2d417"`);
        await queryRunner.query(`ALTER TABLE "response" DROP CONSTRAINT "FK_f6f1d760569e3565113b2806610"`);
        await queryRunner.query(`ALTER TABLE "response" DROP CONSTRAINT "FK_d8eecba590e554b8a3fdaa884f0"`);
        await queryRunner.query(`ALTER TABLE "deal" DROP CONSTRAINT "FK_4e612f6283969396f800e463928"`);
        await queryRunner.query(`ALTER TABLE "deal" DROP CONSTRAINT "FK_2f614e9e5a1934a795c5899ccef"`);
        await queryRunner.query(`ALTER TABLE "deal" DROP CONSTRAINT "FK_cef8a02fad2477f5391c15d28ff"`);
        await queryRunner.query(`ALTER TABLE "deal" DROP CONSTRAINT "FK_bfbf920d6a1138fa110db3e4bac"`);
        await queryRunner.query(`ALTER TABLE "deal" DROP CONSTRAINT "FK_4e3561769b30678661c19bd6c83"`);
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_338e1e9cdacd1d28d7ca9999d8d"`);
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_99f86fa5d1a0f13f9cbbeae3120"`);
        await queryRunner.query(`ALTER TABLE "chat" DROP CONSTRAINT "FK_e263d1c2fdcbc5a97216a28e226"`);
        await queryRunner.query(`ALTER TABLE "ton_top_up" DROP CONSTRAINT "FK_3de8252da69a30a57dcdbe5fb2b"`);
        await queryRunner.query(`ALTER TABLE "stars_top_up" DROP CONSTRAINT "FK_3fe88363a4fa35788cc07495ba6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33030f55bdd02bdb23a0bcdde7"`);
        await queryRunner.query(`DROP TABLE "account"`);
        await queryRunner.query(`DROP TYPE "public"."account_ownertype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."account_purpose_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1b37aa58d62564fe58dd8699d"`);
        await queryRunner.query(`DROP TABLE "balance"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_006353a90dd7cf474171544cc9"`);
        await queryRunner.query(`DROP TABLE "currency"`);
        await queryRunner.query(`DROP TABLE "entry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_279024522b83ec4b7ad9dadd33"`);
        await queryRunner.query(`DROP TABLE "transaction"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_initiatortype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_type_enum"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "arbitration"`);
        await queryRunner.query(`DROP TYPE "public"."arbitration_resolution_enum"`);
        await queryRunner.query(`DROP TYPE "public"."arbitration_status_enum"`);
        await queryRunner.query(`DROP TABLE "chat_message"`);
        await queryRunner.query(`DROP TYPE "public"."chat_message_type_enum"`);
        await queryRunner.query(`DROP TABLE "ton_ignored_transaction"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_languagecode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP TABLE "request"`);
        await queryRunner.query(`DROP TYPE "public"."request_status_enum"`);
        await queryRunner.query(`DROP TABLE "file_attachment"`);
        await queryRunner.query(`DROP TABLE "submission"`);
        await queryRunner.query(`DROP TYPE "public"."submission_status_enum"`);
        await queryRunner.query(`DROP TABLE "response"`);
        await queryRunner.query(`DROP TYPE "public"."response_status_enum"`);
        await queryRunner.query(`DROP TABLE "deal"`);
        await queryRunner.query(`DROP TYPE "public"."deal_escrowstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."deal_status_enum"`);
        await queryRunner.query(`DROP TABLE "chat"`);
        await queryRunner.query(`DROP TABLE "ton_top_up"`);
        await queryRunner.query(`DROP TYPE "public"."ton_top_up_token_enum"`);
        await queryRunner.query(`DROP TABLE "stars_top_up"`);
    }

}
