import type { TaskType } from "../../shared/types"

export const TasksList: TaskType[] = [
  {
    id: "1",
    title: "Take photo of coffee shop menu board",
    description: "Go to BeanCraft and show the full menu board clearly. Payment in escrow.",
    attachments: [
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
    ],
    isUrgent: true,
    mode: "pro",
    price: 20,
    position: { lat: 37.758749, lng: -122.461771 },
    tags: [
      { type: "hLeft", count: 2 },
      { type: "km", count: 1.2 },
    ],
    customer_id: 100,
    performer_id: 200,
    arbitrationApproved: true,
  },
  {
    id: "2",
    title: "Verify store opening hours",
    description: 'Check and capture the posted hours at "Daily Mart". Confirm if holiday hours apply.',
    attachments: [],
    isUrgent: true,
    mode: "base",
    price: 35,
    position: { lat: 37.75254, lng: -122.472629 },
    tags: [{ type: "km", count: 1.2 }],
    customer_id: 100,
    performer_id: 200,
    arbitrationApproved: false,
  },
  {
    id: "3",
    title: "Translate menu from photo",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores odio vel voluptate, cupiditate eveniet est nostrum saepe libero quibusdam aut laborum autem atque rerum harum mollitia nulla nihil, labore accusantium.",
    attachments: [],
    isUrgent: false,
    mode: "base",
    price: 50,
    position: { lat: 37.749859, lng: -122.465076 },
    tags: [{ type: "km", count: 1.2 }],
    customer_id: 200,
    performer_id: 100,
    arbitrationApproved: false,
  },
  {
    id: "4",
    title: "Нужно фото афиши",
    description: "Сделать фото афиши большого театра",
    attachments: [
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
      "https://maisgrelos.com/wp-content/uploads/2024/08/playas-de-mallorca-baleares.jpeg",
    ],
    isUrgent: true,
    mode: "pro",
    price: 50,
    position: { lat: 55.759721, lng: 37.618889 },
    tags: [{ type: "km", count: 1.2 }],
    customer_id: 100,
    performer_id: 200,
    arbitrationApproved: false,
  },
  {
    id: "5",
    title: "Качественные фото памятника",
    description: "Нужны фотографии памятника П.М. Третьякову с разных ракурсов",
    attachments: [],
    isUrgent: true,
    mode: "base",
    price: 35,
    position: { lat: 55.741436, lng: 37.620852 },
    tags: [
      { type: "hLeft", count: 2 },
      { type: "km", count: 1.2 },
    ],
    customer_id: 100,
    performer_id: 200,
    arbitrationApproved: false,
  },
  {
    id: "6",
    title: "Фото фасада",
    description: "Сделать фото фасада храма Георгия Победоносца на Псковской горке",
    attachments: [],
    isUrgent: false,
    mode: "base",
    price: 20,
    position: { lat: 55.75273, lng: 37.630579 },
    tags: [{ type: "km", count: 1.2 }],
    customer_id: 200,
    performer_id: 100,
    arbitrationApproved: false,
  },
]
